#getting base image
FROM ubuntu:18.04

RUN apt-get update

RUN apt -y install curl
#Nodejs Installation
RUN curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt -y install nodejs

#In


CMD [ "echo","test" ]
